inherit: _template_sft.yaml      # keeps common knobs
backbone: Qwen/Qwen2-0.5B        # 🤗 hub id
dataset:  gsm8k_latex     # your pre-processed split

# output
output_dir: "/content/drive/MyDrive/RL_Practice_Files/finetuned/qwen2_gsm8k_lora"

# LoRA + QLoRA
quantized: true      # 4-bit
lora_r: 64
lora_alpha: 128

# optimiser & schedule
batch_size: 16
grad_accum: 2
epochs: 2
lr: 2e-4
lr_scheduler_type: cosine
warmup_ratio: 0.05

# seq-length & packing
max_seq_len: 256
packing: false       # keep CoT examples separate
