# ------------------------------------------------------------------
# keys the trainer expects (tyro parses straight into a dataclass)
# ------------------------------------------------------------------
dataset: gsm8k
backbone: phi2
output_dir: outputs/${dataset}_${backbone}
batch_size: 4
learning_rate: 2e-5
num_epochs: 3
eval_every_steps: 200
generation:
  top_p: 0.9
  temperature: 0.7
lora:
  r: 32
  alpha: 16
  dropout: 0.05
quantized: false            # new
