# default knobs; other YAMLs `inherit` from this
backbone: phi2
dataset: gsm8k
batch_size: 4
epochs: 3
lr: 2e-5
quantized: false
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
grad_accum: 1
save_steps: 500
log_steps: 100
max_seq_len: 1024
