approx_delta_h:
  baseline:
    clip_max: null
    clip_min: null
    ema_beta: 0.9
    fit_dtype: float64
    include_intercept: true
    kind: hk_ema
    normalize: false
    pos_bins: 32
    regression_l2: 0.0
  curvature:
    enabled: true
  method: jvp
  microbatch_size: 8
  normalize: per_token
  report_per_token: false
  ridge:
    eps: 1.0e-08
    lambda: 0.001
  simple_baseline:
    kind: time_loo
  variance:
    enabled: true
    jackknife: true
batch_config:
  B_E: 2048
  B_U: 64
  E_split: train
  G: 8
  U_split: test
  dataset_name: gsm8k_r1_template
checkpoint:
  backbone: qwen2_5_15
  checkpoint_path: /content/drive/MyDrive/RL_Practice_Files/new_rl_checkpoint/step_40/model
  device_map: cuda
  optimizer_path: /content/drive/MyDrive/RL_Practice_Files/new_rl_checkpoint/step_40/optimizer.pt
detailed_logging:
  compress: true
  enabled: true
  level: standard
  log_raw_tensors: false
  log_sequences: false
  log_tokens: false
  max_files: 50
  output_directory: entropy_experiments/logs
estimator:
  eta_list:
  - 8e-7
  - 1.6e-06
  - 3.2e-06
  - 6.4e-06
  - 1.28e-05
  eta_sweep: true
  single_eta: 4e-6
  use_simple_entropy_for_x: false
generation:
  gen_batch_size: 128
  max_new_tokens: 150
  temperature: 1.0
  tf_batch_size: 16
  top_p: 1.0
output:
  log_level: INFO
  results_path: ''
precision:
  allow_tf32: false
  entropy_dtype: float64
  matmul_precision: high
  runtime_dtype: float32
  tf_withgrad:
    autocast: false
    cast_logits_fp32: true
    dtype: float32
  update_vector:
    amp_dtype: bfloat16
    grads_fp32: true
    use_amp: false
rb_requires_grad: true
true_delta_h:
  clip_c: 10.0
  is_mode: snis
  microbatch_size: 1
  report_per_token: true
  snapshot_device: cpu
  tf_batch_size: 8
