# 🧪 Debug Configuration - Memory Optimized
# Optimized for debugging bars_dot with minimal memory usage

# Core batch configuration - small sizes for debugging
batch_config:
  B_E_values: [16]                     # Single small B_E value
  B_U: 16                              # Reduced B_U
  runs_per_batch: 1                    # Single run for debugging
  G: 4                                 # Reduced generations
  rollout_batch_size: 32               # Smaller rollout batch
  dataset_name: "gsm8k_r1_template"
  split: "train"

# Probe computation mode
probe_config:
  mode: "exact"
  M: null

# Probe analysis - memory optimized
probe_rework:
  mb_size_prompts: 2                   # Small microbatches for main computation
  buffers_dtype: "float32"
  weighting_mode: "dr_grpo"
  conditional_variance_batch_size: 1   # Single prompt at a time to avoid OOM
  
  # Focus on conditional variance only
  compute_vx_vy_variance: false
  compute_conditional_variance: true
  compute_importance_sampling: false
  
  ddp_allreduce: false
  master_seed: 42

# Single-GPU settings
distributed:
  find_unused_parameters: false
  reduce_dtype: "float32"
  barriers: false

# Disable importance sampling for simplicity
importance:
  enabled: false

importance_sampling:
  use_snis: true
  use_psis: false
  ess_threshold: 0.5
  resample_on_low_ess: false

# Statistics configuration
stats_config:
  compute_plugin_se: true
  compute_jackknife_se: false

# Memory settings - conservative for debugging
memory_config:
  microbatch_size: 2
  teacher_force_microbatch_size: 2
  amp: true
  dtype: "bfloat16"

learning_rate: 2e-6

checkpoint:
  checkpoint_path: ""
  optimizer_path: ""
  model_config_path: "Qwen/Qwen2.5-1.5B"

generation:
  max_new_tokens: 50                   # Keep existing for now
  temperature: 1.0                     # Higher temperature for diversity
  top_p: 1.0
  do_sample: true
  pad_token_id: null

output:
  save_results: true
  results_path: ""
  log_level: "DEBUG"                   # Debug logging to see advantages
  save_samples: false