# Multi-Checkpoint Entropy Analysis Configuration

entropy_sweep:
  # Checkpoint selection
  checkpoints:
    # Option 1: Specify explicit checkpoint paths
    paths: []
    # Option 2: Auto-discover from training run
    training_run: ""          # e.g., "run_2025-08-19_23-46-27"
    step_pattern: "step_*"    # Pattern to match checkpoint directories
    max_checkpoints: 10       # Limit number of checkpoints to analyze
  
  # Analysis configuration (inherits from fisher_analysis.yaml)
  base_config: "fisher_analysis.yaml"
  
  # Sweep-specific overrides
  analysis:
    eval_batch_size: 64       # Smaller batches for multiple checkpoints
    train_batch_size: 128
    
    # Track Fisher kernel evolution
    kernel_evolution: true
    eigenvalue_analysis: true
    prompt_clustering_evolution: true
    
  # Output
  output:
    results_dir: "results/sweep_${timestamp}"
    save_evolution_plots: true
    save_summary_report: true