# Fisher Analysis Configuration

entropy_analysis:
  # Sampling configuration
  eval_batch_size: 128      # Sequences for E_t[...] computation
  train_batch_size: 256     # Sequences for training updates
  
  sampling:
    eval_prompts: "random"   # "random" or "fixed_set"
    train_prompts: "random"  # "random" or "fixed_set"
    same_prompts: false      # Whether eval and train can overlap
    num_generations: 8       # Generations per prompt
    max_new_tokens: 100      # Max generation length
    temperature: 0.7         # Sampling temperature
  
  # Fisher kernel computation
  fisher_kernel:
    compute_full: true       # Compute full cross-kernel
    save_gradients: true     # Save individual gradients for analysis
    preconditioning: "checkpoint"  # "none", "checkpoint", "previous_step"
    chunk_size: 32           # Process gradients in chunks (memory management)
  
  # Analysis options
  analysis:
    prompt_structure: true   # Analyze same-prompt vs different-prompt
    sequence_clustering: true # Cluster sequences by Fisher similarity
    entropy_prediction: true # Validate entropy change predictions
    save_detailed: true      # Save detailed analysis results
    
  # Output configuration
  output:
    save_fisher_kernel: true
    save_gradients: false    # Large files - only enable if needed
    save_analysis: true
    results_dir: "results"