# 🧪 Lambda Medium-Scale Test Config (Stage 1 Testing)
# Half the production batch sizes, single E-batch for faster testing
# Tests numerical stability fix while being reasonably fast

# === MODEL AND CHECKPOINT ===
checkpoint:
  checkpoint_path: "/home/ubuntu/localfs/training_runs/run_2025-09-03_03-59-57/training_state/step_40/model"
  optimizer_path: "/home/ubuntu/localfs/training_runs/run_2025-09-03_03-59-57/training_state/step_40/optimizer.pt"
  backbone: "qwen2_5_15"
  dtype: "bfloat16"
  device_map: "cuda"

# === BATCH CONFIGURATION ===
batch_config:
  dataset_name: "gsm8k_r1_template"
  E_split: "test"   # Evaluation batch uses test set
  U_split: "train"  # Update batch uses train set
  B_E: 256         # Half of production (was 512)
  B_U: 32          # Half of production (was 64)
  G: 8             # Number of responses per prompt (U batch)

# === COMPUTATION OPTIONS ===
computation_options:
  compute_delta_h1: true
  master_seed: none
  mb_size_prompts: 1      # Conservative: 1 for memory efficiency
  weighting_mode: "dr_grpo"

# === GROUND TRUTH ENTROPY CHANGE ===  
true_delta_h:
  enabled: true                   # Required for testing Stage 1 fix
  training_loss: "rl"
  microbatch_size: 1              # Conservative: 1 for memory efficiency
  clip_c: 10.0
  report_per_token: true

# === GENERATION SETTINGS ===  
generation:
  temperature: 1.0                # temp=1.0 to avoid measure mismatch issues
  top_p: 0.995  
  max_new_tokens: 150
  gen_batch_size: 32              # Half of production (was 64)
  tf_batch_size: 4                # Conservative for memory

# === MEMORY CONFIGURATION ===
memory_config:
  amp: true
  dtype: "bfloat16" 
  microbatch_size: 1              # Conservative: 1 for memory efficiency

# === DETAILED LOGGING ===
detailed_logging:
  enabled: true
  level: "standard"               # To see the new ESS diagnostics
  log_sequences: false            # Disable to save time
  log_tokens: false               
  log_raw_tensors: false         
  output_directory: "entropy_experiments/logs"
  compress: true
  max_files: 50

# === OUTPUT CONFIGURATION ===
output:
  log_level: "INFO"
  results_path: ""

# === TEST GOALS ===
# 1. Test Stage 1 numerical stability fix (float64 + global max)
# 2. Should see reasonable H_upd (not doubled like before)
# 3. Monitor ESS fraction (should be > 5% for healthy IS)
# 4. Run time: ~15-20 minutes (vs 30+ for full production)