# 🧪 Lambda Test with top_p=0.9999
# Testing if top-p truncation is causing ESS collapse

# === MODEL AND CHECKPOINT ===
checkpoint:
  checkpoint_path: "/home/ubuntu/localfs/training_runs/run_2025-09-03_03-59-57/training_state/step_40/model"
  optimizer_path: "/home/ubuntu/localfs/training_runs/run_2025-09-03_03-59-57/training_state/step_40/optimizer.pt"
  backbone: "qwen2_5_15"
  dtype: "bfloat16"
  device_map: "cuda"

# === BATCH CONFIGURATION ===
batch_config:
  dataset_name: "gsm8k_r1_template"
  E_split: "test"   # Evaluation batch uses test set
  U_split: "train"  # Update batch uses train set
  B_E: 128         # Medium batch size
  B_U: 16          # Small U batch
  G: 8             # Number of responses per prompt (U batch)

# === COMPUTATION OPTIONS ===
computation_options:
  compute_delta_h1: true
  master_seed: none
  mb_size_prompts: 1
  weighting_mode: "dr_grpo"

# === GROUND TRUTH ENTROPY CHANGE ===  
true_delta_h:
  enabled: true
  training_loss: "rl"
  microbatch_size: 1
  clip_c: 10.0
  report_per_token: true
  measure: "q"  # Use q measure for IS

# === GENERATION SETTINGS ===  
generation:
  temperature: 1.0
  top_p: 0.9999     # CRITICAL: Nearly 1.0 to avoid nucleus truncation issues
  max_new_tokens: 100
  gen_batch_size: 32
  tf_batch_size: 4

# === MEMORY CONFIGURATION ===
memory_config:
  amp: true
  dtype: "bfloat16" 
  microbatch_size: 1

# === DETAILED LOGGING ===
detailed_logging:
  enabled: true
  level: "standard"
  log_sequences: false
  log_tokens: false
  log_raw_tensors: false
  output_directory: "entropy_experiments/logs"
  compress: true
  max_files: 50

# === OUTPUT CONFIGURATION ===
output:
  log_level: "INFO"
  results_path: ""

# === TEST HYPOTHESIS ===
# If top_p=0.995 was causing tokens to fall outside nucleus
# after model update, then top_p=0.9999 should improve ESS
# dramatically (from ~1% to potentially >10%)